python -m upgrade_v2.u3.cli refine-prompt-once ...
python -m upgrade_v2.u3.cli validate-prompt-package --expected-count 3 ...
python -m upgrade_v2.u3.cli build-provider-request-table --expected-count 3 ...
