#!/usr/bin/env bash
set -euo pipefail

export REPO_ROOT="${REPO_ROOT:-/home/__compress_data/xushijie/CUPID}"
cd "$REPO_ROOT"
export PYTHON_BIN="${PYTHON_BIN:-/home/xushijie/.conda/envs/cupid/bin/python}"
export PYTHONPATH="$REPO_ROOT${PYTHONPATH:+:$PYTHONPATH}"
export STAGE3_ROOT="$REPO_ROOT/artifacts/pathgraph_sarm/stage3"
export STAGE3_DIAG="$STAGE3_ROOT/diagnostic_suite_v1"
export STAGE3_INPUT="$STAGE3_ROOT/input_adapter_v1"
export STAGE4_ROOT="$REPO_ROOT/artifacts/pathgraph_sarm/stage4"
export STAGE4_SUPERVISION="${STAGE4_SUPERVISION:-$STAGE4_ROOT/supervision_v1}"
export STAGE5_ROOT="$REPO_ROOT/artifacts/pathgraph_sarm/stage5"
export STAGE5_PRED="$STAGE5_ROOT/real_predictions_v1"
export STAGE5_REWARD="$STAGE5_ROOT/reward_v1"
export STAGE5_TOOLS="$REPO_ROOT/tools/stage5"
export STAGE6_ROOT="$REPO_ROOT/artifacts/pathgraph_sarm/stage6"
export STAGE6_PERSISTENT="$STAGE6_ROOT/stage6_inputs/reward_v1_persistent"
export STAGE7_ROOT="$REPO_ROOT/artifacts/pathgraph_sarm/stage7_reward_only"
export STAGE7_ROUNDS="$STAGE7_ROOT/rounds"
export STAGE7R1_ROOT="$REPO_ROOT/artifacts/pathgraph_sarm/stage7_refine1"
export STAGE7R1_G4="$STAGE7R1_ROOT/g4_refine1_v1"
export STAGE7R1_FINAL="$STAGE7R1_ROOT/final_package"
export STAGE8_ROOT="${STAGE8_ROOT:-$REPO_ROOT/artifacts/pathgraph_sarm/stage8_core_reward}"
export STAGE8_INPUTS="$STAGE8_ROOT/final_inputs_v1"
export STAGE8_REPRO="$STAGE8_ROOT/core_reproduction_v1"
export STAGE8_STATS="$STAGE8_ROOT/final_statistics_v1"
export STAGE8_PAPER="$STAGE8_ROOT/paper_artifacts_v1"
export STAGE8_RELEASE="$STAGE8_ROOT/reproducibility_release_v1"
export STAGE8_M6="$STAGE8_ROOT/m6_final_v1"
export STAGE8_ROUNDS="$STAGE8_ROOT/rounds"
export STAGE8_TOOLS="$REPO_ROOT/tools/stage8"
export STAGE8_DOWNLOADS="${STAGE8_DOWNLOADS:-$REPO_ROOT/downloads/stage8}"
export GPU_MIN_FREE_MB="${GPU_MIN_FREE_MB:-8000}"
export MAX_JOBS_PER_GPU="${MAX_JOBS_PER_GPU:-1}"
export ZIP_MAX_FILE_MB="${ZIP_MAX_FILE_MB:-200}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-4}"
export FINAL_BOOTSTRAP_RESAMPLES="${FINAL_BOOTSTRAP_RESAMPLES:-10000}"
export FINAL_BOOTSTRAP_SEED="${FINAL_BOOTSTRAP_SEED:-20261401}"

mkdir -p "$STAGE8_INPUTS" "$STAGE8_REPRO" "$STAGE8_STATS" "$STAGE8_PAPER" \
  "$STAGE8_RELEASE" "$STAGE8_M6" "$STAGE8_ROUNDS" "$STAGE8_TOOLS" "$STAGE8_DOWNLOADS"
