from __future__ import annotations
RC1_STAGES = ["WAIT_REHOLD_STABLE","ESTIMATE_ATTACHMENT","PLAN_RETURN","XY_ALIGN","SETTLE_AND_VERIFY"]
RC2_STAGES = ["WAIT_REHOLD_STABLE","ESTIMATE_ATTACHMENT","PLAN_RETURN","SAFE_CLEARANCE","XY_ALIGN","Z_ALIGN","SETTLE_AND_VERIFY"]
RC3_STAGES = ["WAIT_REHOLD_STABLE","ESTIMATE_ATTACHMENT","PLAN_RETURN","SAFE_CLEARANCE","XY_ALIGN","Z_ALIGN","FINE_SERVO","SETTLE_AND_VERIFY"]
BUDGET_S = {"SAFE_CLEARANCE": 0.35, "XY_ALIGN": 0.80, "Z_ALIGN": 0.45, "FINE_SERVO": 0.40, "SETTLE_AND_VERIFY": 0.20}

def stages_for(controller_id: str):
    if controller_id == "RC1_OBJECT_COMPENSATED_DIRECT":
        return list(RC1_STAGES)
    if controller_id == "RC2_OBJECT_COMPENSATED_STAGED":
        return list(RC2_STAGES)
    if controller_id == "RC3_OBJECT_ERROR_SERVO":
        return list(RC3_STAGES)
    raise ValueError(controller_id)
