#!/usr/bin/env bash
set -euo pipefail

export REPO_ROOT="$(git rev-parse --show-toplevel)"
export ENTRY_COMMIT="5a3aafd6ac6d139ba324ee57110bbac508e17570"
export PYTHON_BIN="${PYTHON_BIN:-/home/xushijie/.conda/envs/lerobot/bin/python}"
export L1V_ROOT="$REPO_ROOT/artifacts/pathgraph_sarm/upgrade_v2/visual_coarse_l1_v1"
export L1V_RUN="$L1V_ROOT/run"
export L1V_REVIEW="$L1V_ROOT/review_v2"
export L1V_METRICS="$L1V_ROOT/metrics_v2"
export L1V_ENTRY="$L1V_ROOT/layer2_entry_v1"
export L2R_ROOT="$REPO_ROOT/artifacts/pathgraph_sarm/upgrade_v2/visual_refine_l2_v1"
export L2R_PROTOCOL="$L2R_ROOT/protocol_v1"
export L2R_COARSE="$L2R_ROOT/coarse_graph_v1"
export L2R_DATA="$L2R_ROOT/dynamic_dataset_v1"
export L2R_VISION="$L2R_ROOT/observable_predicates_v1"
export L2R_GRAPHS="$L2R_ROOT/refined_graphs_v1"
export L2R_CONFIRM="$L2R_ROOT/fresh_confirmation_v1"
export L2R_FINAL="$L2R_ROOT/final_v1"
export L2R_ROUNDS="$L2R_ROOT/rounds"
export L2R_TOOLS="$REPO_ROOT/upgrade_v2/visual_refine_l2"
export L2R_DOWNLOADS="${L2R_DOWNLOADS:-$REPO_ROOT/downloads/l2r}"
export CPU_WORKERS="${CPU_WORKERS:-4}"
export MAX_JOBS_PER_GPU="${MAX_JOBS_PER_GPU:-1}"
export GPU_MIN_FREE_MB="${GPU_MIN_FREE_MB:-6000}"
export ZIP_MAX_FILE_MB="${ZIP_MAX_FILE_MB:-200}"
export MUJOCO_GL="${MUJOCO_GL:-egl}"
export MUJOCO_EGL_DEVICE_ID="${MUJOCO_EGL_DEVICE_ID:-0}"

mkdir -p "$L2R_ROOT" "$L2R_PROTOCOL" "$L2R_COARSE" "$L2R_DATA" "$L2R_VISION" "$L2R_GRAPHS" "$L2R_CONFIRM" "$L2R_FINAL" "$L2R_ROUNDS" "$L2R_DOWNLOADS"
