#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
import pandas as pd
def main():
 p=argparse.ArgumentParser();p.add_argument('--seed-effects',type=Path,required=True);p.add_argument('--bootstrap',type=Path,required=True);p.add_argument('--replication',type=Path,required=True);p.add_argument('--evaluation-lock',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--report',type=Path,required=True);a=p.parse_args();s=pd.read_csv(a.seed_effects);b=pd.read_csv(a.bootstrap);rep=json.loads(a.replication.read_text());ev={r.metric:r for r in b.itertuples(index=False)}
 def row(m):return ev[m]
 e={'new_seed_improved_count':rep['new_seed_improved_count'],'new_seed_ceiling_tie_count':rep['new_seed_ceiling_tie_count'],'new_seed_degraded_count':rep['new_seed_degraded_count'],'combined_graph_task_success_gain':row('graph_task_success').difference,'combined_graph_task_success_ci95':[row('graph_task_success').ci95_low,row('graph_task_success').ci95_high],'combined_recovery_success_gain':row('recovery_success').difference,'combined_recovery_success_ci95':[row('recovery_success').ci95_low,row('recovery_success').ci95_high],'combined_worst_order_success_gain':row('worst_order_success').difference,'combined_worst_order_success_ci95':[row('worst_order_success').ci95_low,row('worst_order_success').ci95_high],'combined_long_horizon_completion_gain':row('long_horizon_completion').difference,'combined_fixed_order_drop':max(0.,-row('fixed_order_success').difference),'combined_fixed_order_gain':row('fixed_order_success').difference,'combined_seed_count':int(s.policy_seed.nunique()),'paired_evaluation':json.loads(a.evaluation_lock.read_text()).get('paired_evaluation') is True,'reward_retuned_after_test':False,'bootstrap_resamples':int(row('graph_task_success').resamples),'locked_comparator':'linear_sarm_equiv','evidence_source':'six_seed_raw_paired_rollouts'};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(e,indent=2)+'\n');a.report.write_text('# G3-R1 evidence summary\n\n'+json.dumps(e,indent=2)+'\n');print(json.dumps(e,indent=2))
if __name__=='__main__':main()
