#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
import pandas as pd,yaml
def main():
 p=argparse.ArgumentParser();p.add_argument('--g3',type=Path,required=True);p.add_argument('--input-lock',type=Path,required=True);p.add_argument('--protocol',type=Path,required=True);p.add_argument('--seed-registry',type=Path,required=True);p.add_argument('--rule',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--report',type=Path,required=True);a=p.parse_args();g=json.loads(a.g3.read_text());pr=yaml.safe_load(a.protocol.read_text());s=pd.read_csv(a.seed_registry);r=json.loads(a.rule.read_text());
 checks={'parent_decision_refine':g['decision']=='REFINE_STAGE6','graph_gain_ge_0_05':g['checks']['graph_gain_ge_0_05'] is True,'only_seed_gate_failed':g['checks']['improved_seeds_ge_2'] is False and all(g['checks'][k] for k in ('fixed_order_drop_le_0_05','structure_specific_gain','no_post_test_reward_retune')),'input_lock_complete':json.loads(a.input_lock.read_text()).get('locked') is True,'new_seeds_exact':set(s.policy_seed)=={20260912,20260913,20260914} and len(s)==6,'comparator_locked':r['comparison']['method_b']=='linear_sarm_equiv','rule_locked_before_training':r['locked_before_new_training'] is True,'frozen_fields':pr['optimization']['total_optimizer_steps']==2000 and pr['optimization']['batch_size']==32 and pr['optimization']['effective_batch_size']==32 and pr['data']['weighted_sampling'] is False and pr['data']['test_for_selection'] is False}
 decision='REFINE1_PROTOCOL_LOCKED' if all(checks.values()) else 'FIX_PROTOCOL_FILES';result={'decision':decision,'checks':checks,'new_training_allowed':decision=='REFINE1_PROTOCOL_LOCKED'};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(result,indent=2)+'\n');a.report.write_text('# R1 protocol summary\n\nDecision: `'+decision+'`\n\nOnly new policy seeds 20260912, 20260913, and 20260914 are added. Reward, gamma, data, budget, comparator, and evaluation definitions remain frozen.\n');print(json.dumps(result,indent=2));return 0 if decision.endswith('LOCKED') else 2
if __name__=='__main__':raise SystemExit(main())
