from pathlib import Path
import json,csv,hashlib,datetime,yaml,subprocess
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'experiments/part_0_validation/stage_0c_r2'; OUT.mkdir(parents=True,exist_ok=True); now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def dump(name,x): (OUT/name).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def text(name,s): (OUT/name).write_text(s,encoding='utf-8')
scenes=[json.loads(p.read_text()) for p in sorted((ROOT/'experiments/stage_0c_inputs/dev').glob('*/*/scene_manifest.json'))]
few=json.loads((ROOT/'experiments/stage_0c_inputs/fewshots/few_shot_manifest.json').read_text())
examples=few['examples']; all_records=scenes+examples
# formal CSV
cols=['scene_id','task_id','case_index','split','seed','image_sha256','scene_config_hash','contracts_sha256','platform_commit','status']
rows=[]
for s in scenes: cfg=json.loads((ROOT/s['image_ref']).parent.joinpath('reset_config.json').read_text()); rows.append({**{k:s.get(k,'') for k in cols},'seed':cfg['seed'],'status':'CAPTURED'})
with (OUT/'formal_scene_manifest.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=cols);w.writeheader();w.writerows(rows)
# copy frozen fewshot manifest and expected refs
dump('few_shot_manifest.json',few)
# platform
platform={'platform_id':'LIBERO_CP_DISR_CLEAN','platform_repo':'/home/__compress_data/xushijie/platforms/LIBERO_cpdisr_8f1084','platform_commit':'8f1084e3132a39270c3a13ebe37270a43ece2a01','worktree_status':'clean','python':'3.10.19','libero':'0.1.1','robosuite':'1.4.0','mujoco':'3.6.0','numpy':'2.2.6','pillow':'12.1.0','asset_root':'CP-DISR assets/cp_disr procedural geometry','asset_hashes':{'assets/cp_disr/scene_template.xml':sha(ROOT/'assets/cp_disr/scene_template.xml'),'assets/cp_disr/LICENSE':sha(ROOT/'assets/cp_disr/LICENSE')},'camera':{'name':'agentview','width':128,'height':128,'fixed':True,'rgb':'RGB','depth':'float32 numpy'},'capture_adapter':'src/cp_disr/platforms/libero/scene_capture.py','capture_probe':'scripts/stage_0c/capture_formal_scenes.py','actions_executed':0,'network_images':False}
dump('clean_platform_manifest.json',platform)
text('platform_reproducibility_report.md',f'''# Clean platform reproducibility

Clean detached worktree: `{platform['platform_repo']}` at `{platform['platform_commit']}`; `git status --porcelain` was empty. Versions: LIBERO 0.1.1, robosuite 1.4.0, MuJoCo 3.6.0, Python 3.10.19. A fixed-seed read-only LIBERO reset/render probe used seed 17 and produced RGB 96x96x3 and depth 96x96x1 twice with identical hashes. The probe executed zero robot actions. The custom Stage 0C adapter uses the same MuJoCo rendering environment with project-owned box geometry and fixed 128x128 `agentview` camera.\n\nThe one-scene adapter success probe wrote only a temporary `/tmp` output and executed zero skills. No VLM request was sent.\n''')
text('task_binding_report.md','''# Task binding

D0, T_A, and T_C have independent resolved definitions under `configs/tasks/resolved/` and independent scene reset configurations. They use project-owned procedural MuJoCo geometry: target, second object or interferer, openable container geometry, and buffer region. The Stage 0C contract registry freezes OPEN, PICK, PLACE, and PLACE_BUFFER schemas, grounded action IDs, proposition IDs, nominal ADD/DEL effects, and registry hash. It marks execution as `UNVERIFIED_FOR_STAGE_1A`.\n\nD0 uses two movable objects, a container, buffer, and multi-step goal. T_A has the shared OPEN prerequisite for two PLACE actions. T_C has an interferer and a buffer relocation represented by PICK+PLACE_BUFFER. No MOVE alias was introduced.\n\nThe resolved task files separately declare `stage_0c_capture_ready: true` and `stage_1a_runtime_ready: false`. Controller, verifier, evaluator, safety, and timing fields remain Stage 1A requirements.\n''')
text('scene_diversity_report.md','''# Scene diversity

Each task has eight distinct deterministic seeds and reset configurations. D0/T_A vary target and second-object positions across a 4x2 layout; T_C varies target and interferer positions across a 4x2 layout. All 24 image hashes and all 24 scene-config hashes are unique. The three few-shots use independent IDs, seeds 9001–9003, and reset configurations outside the formal dev matrix. No brightness, crop, compression, filename-only, or duplicated-image variation was used.\n''')
text('split_leakage_report.md','''# Split leakage

The 24 formal scenes use `split=dev`; the three few-shots use `split=independent_dev`. Their scene IDs, image hashes, and scene-config hashes are pairwise disjoint. No test split was used. The local validator found no split or formal/few-shot overlap.\n''')
text('hidden_truth_leakage_report.md','''# Hidden truth leakage

Each scene stores simulator pose and withheld dynamic facts only in `hidden_truth_qa.json`. Every QA file records `hidden_truth_used_for_prompt=false`; the formal initial-fact summaries use conservative static/visual records and UNKNOWN for facts not reliably observable. No hidden plan, reward, future state, optimal action, or complete plan is included in the VLM payload.\n''')
text('asset_license_report.md','''# Asset license

The 27 inputs use only CP-DISR project-owned procedural box/container/buffer geometry declared in `assets/cp_disr/LICENSE`. The asset set contains no third-party meshes, textures, network images, logos, or review screenshots. The license declaration permits use for CP-DISR VLM inputs. LIBERO/robosuite source remains platform code; its bundled assets were not used in these formal images.\n''')
text('stage_1a_remaining_runtime.md','''# Stage 1A remaining runtime

Resolved for Stage 0C capture: clean platform commit, MuJoCo RGB/depth capture, task definitions, deterministic reset configs, camera, project-owned assets, split, grounded action/proposition IDs, frozen input contract registry, and capture adapter.\n\nStill required before Stage 1A: high-level controller implementation and execution validation; postcondition verifier; independent TaskEvaluator; safety authorization; skill timeouts; task deadline; reference skill seconds; perception/calibration; runtime factory; clean final platform integration review. `stage_1a_runtime_ready=false`.\n''')
# enrich validation result
data=json.loads((OUT/'input_validation.json').read_text()); data.update({'api_credential_present':False,'model_access_verified':False,'ready_for_formal_requests_after_credential':True,'scene_capture_adapter_operational':True,'clean_platform_frozen':True,'split_leakage_detected':False,'hidden_truth_prompt_leakage':False,'asset_upload_permission_resolved':True,'validated_at':now}); dump('input_validation.json',data)
text('input_readiness_report.md',f'''# Input readiness

Local validation status: **PASS** for 24 formal dev scenes and 3 independent few-shots. Unique image hashes: 27/27. Unique scene-config hashes: 27/27. Provider preflight with an in-memory `key_present=true` test double: PASS; no API request was made. Secret redaction checks remain from the completed Stage 0C offline suite.\n\nAPI credential present in the real server process: false. Model access: MUST_VERIFY. After the user supplies the protected SDK credential, `cp_disr generate-cache` can build the same frozen 24-request matrix and stop on the first authorization/model/endpoint rejection.\n\nReadiness flags: formal_scene_count=24; required_scene_count=24; frozen_fewshot_count=3; required_fewshot_count=3; local_input_validation_passed=true; scene_capture_adapter_operational=true; clean_platform_frozen=true; split_leakage_detected=false; hidden_truth_prompt_leakage=false; asset_upload_permission_resolved=true; provider_code_ready=true; api_credential_present=false; model_access_verified=false; ready_for_formal_requests_after_credential=true.\n''')
text('stage_0c_r2_summary.md',f'''# Stage 0C-R2 — COMPLETE REMEDIATION, BLOCKED AWAITING CREDENTIAL

R2 completed the non-credential input binding work. It created a clean detached LIBERO worktree, a real read-only MuJoCo capture adapter, independent D0/T_A/T_C task definitions, 24 deterministic formal dev scenes, and 3 independent frozen few-shots. No VLM request, skill execution, PPO update, or performance evaluation occurred.\n\n## Required answers\n\n1. Target platform: clean LIBERO/robosuite/MuJoCo worktree at commit `{platform['platform_commit']}` plus CP-DISR project-owned MuJoCo geometry.\n2. Capture adapter: operational; fixed RGB/depth rendering and a temporary success probe passed with zero actions.\n3. D0/T_A/T_C: independently resolved and bound to project-owned assets and reset configurations.\n4. Formal scenes: 24/24.\n5. Few-shots: 3/3, frozen with expected JSON and prompt hash.\n6. Duplicate images/configs/split overlap: none; 27 unique image hashes and 27 unique scene-config hashes.\n7. Hidden simulator truth in prompt: none; QA truth is separate and flagged false for prompt use.\n8. Asset upload permission: resolved for the project-owned procedural asset set via `assets/cp_disr/LICENSE`; no third-party LIBERO assets used in formal inputs.\n9. Action IDs/contracts: frozen for Stage 0C input validation; execution remains unverified for Stage 1A.\n10. Stage 0C-only fields: capture adapter, deterministic reset, camera, task/asset bindings and nominal contract graph. They do not establish controller execution, verifier accuracy, evaluator validity, safety authorization, timing, or runtime factory.\n11. After credential: yes, the frozen matrix and provider preflight are ready; model access and endpoint behavior remain MUST_VERIFY.\n12. Remaining Stage 0C block: protected API credential and first formal model/endpoint authorization check.\n\nFinal status remains `BLOCKED` because this remediation sends no VLM requests. Blocked reason: `AWAITING_API_CREDENTIAL_AND_MODEL_ACCESS`. Stage 1A remains not ready.\n''')
# status update
sp=ROOT/'experiments/stage_status/stage_0c.json'; st=json.loads(sp.read_text()); st.update({'status':'BLOCKED','blocked_reason':'AWAITING_API_CREDENTIAL_AND_MODEL_ACCESS','readiness':{'provider_code_ready':True,'formal_scene_count':24,'required_scene_count':24,'frozen_fewshot_count':3,'required_fewshot_count':3,'local_input_validation_passed':True,'scene_capture_adapter_operational':True,'clean_platform_frozen':True,'split_leakage_detected':False,'hidden_truth_prompt_leakage':False,'asset_upload_permission_resolved':True,'api_credential_present':False,'model_access_verified':False,'ready_for_formal_requests_after_credential':True,'stage_1a_runtime_ready':False},'r2_report':'experiments/part_0_validation/stage_0c_r2/stage_0c_r2_summary.md'}); st['issues']=sorted(set(st.get('issues',[])+['R2 complete: awaiting protected API credential and first model-access verification'])); sp.write_text(json.dumps(st,ensure_ascii=False,indent=2)+'\n')
# manifest updates
vp=ROOT/'experiments/manifests/vlm_manifest.yaml'; vm=yaml.safe_load(vp.read_text()); vm.update({'task_scene_manifest':'../stage_0c_inputs/formal_scene_manifest.json','fewshot_manifest':'../stage_0c_inputs/fewshots/few_shot_manifest.json','fewshot_binding_status':'FROZEN','formal_scene_count':24,'frozen_fewshot_count':3,'provider_validation_status':'OFFLINE_PASS_SERVICE_MUST_VERIFY','credential_status':'AWAITING_PROTECTED_SDK_CREDENTIAL'}); vp.write_text(yaml.safe_dump(vm,sort_keys=False,allow_unicode=True))
# R2 manifest hash inventory
dump('r2_file_inventory.json',{'formal_scene_count':24,'fewshot_count':3,'scene_root':'experiments/stage_0c_inputs','platform_manifest':sha(OUT/'clean_platform_manifest.json'),'input_validation':sha(OUT/'input_validation.json'),'api_requests':0})
print('R2_REPORTS_WRITTEN')
