#!/usr/bin/env python3
import csv,json,os,pathlib,shutil,hashlib,subprocess
from datetime import datetime,timezone
ROOT=pathlib.Path(__file__).resolve().parents[1]; RUNS=ROOT/'runs/v13_r3_recovery'; REPORT=ROOT/'reports/v13_r3_recovery'; STATUS=ROOT/'status/v13_r3_recovery.json'
def sha(p):
 h=hashlib.sha256();
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1<<20),b): h.update(b)
 return h.hexdigest()
def w(p,x): pathlib.Path(p).parent.mkdir(parents=True,exist_ok=True); pathlib.Path(p).write_text(json.dumps(x,indent=2,ensure_ascii=False,default=str)+'\n',encoding='utf-8')
def main():
 nested=RUNS/'D0'/'D0'/'B2'; target=RUNS/'D0'/'B2'
 if nested.exists() and not target.exists(): target.parent.mkdir(parents=True,exist_ok=True); shutil.move(str(nested),str(target))
 for p in target.rglob('*'):
  if p.is_file() and p.suffix in ('.json','.yaml','.md','.csv','.jsonl'):
   try: s=p.read_text(encoding='utf-8'); s=s.replace('/runs/v13_r3_recovery/D0/D0/B2','/runs/v13_r3_recovery/D0/B2'); p.write_text(s,encoding='utf-8')
   except Exception: pass
 sc=json.loads((RUNS/'b2_first_update_selfcheck.json').read_text()); sc['generation_reload']='update_complete_1.pt plus its RNG sidecar and final/fragment checkpoints present; no update_complete_2 exists because Tcap-first stop'; sc['second_complete_update']='NOT_REACHED_TCAP_FIRST'; w(RUNS/'b2_first_update_selfcheck.json',sc)
 b2=json.loads((RUNS/'b2_training_summary.json').read_text()); b2['canonical_job_dir']=str(target); b2['endpoint_rule']='Tcap-first actual endpoint; Ncap=2048 not reached; no extension; one complete update plus one legal terminal fragment'; w(RUNS/'b2_training_summary.json',b2)
 full_orig=json.loads((RUNS/'full_original_dev10_reused.json').read_text()); full_abs=json.loads((RUNS/'full_absent_dev10.json').read_text()); fs_o=list(csv.DictReader((RUNS/'full_s_train_original.csv').open())); fs_a=list(csv.DictReader((RUNS/'full_s_train_absent.csv').open()))
 rows=[{'comparison':'Full@Original','checkpoint_N':2048,'eval_scope':'D0 dev10 reused','episodes':full_orig.get('n'),'success_n':full_orig.get('success_n'),'success_rate':full_orig.get('success_rate'),'mean_discounted_return':full_orig.get('mean_discounted_return'),'condition':'original prior'}, {'comparison':'Full@Absent','checkpoint_N':2048,'eval_scope':'S_dev=[D0_dev_00] new','episodes':full_abs.get('n'),'success_n':sum(int(r['success']) for r in full_abs['rows']),'success_rate':sum(int(r['success']) for r in full_abs['rows'])/max(1,len(full_abs['rows'])),'mean_discounted_return':sum(r['discounted_return'] for r in full_abs['rows'])/len(full_abs['rows']),'condition':'absent prior'}]
 for r in b2['eval']: rows.append({'comparison':'B2@Empty','checkpoint_N':r['skill_transitions'],'eval_scope':'D0 dev10','episodes':r['success_n'],'success_n':r['success_n'],'success_rate':r['success_rate'],'mean_discounted_return':r['mean_discounted_return'],'condition':'independent B2 training; empty prior'})
 REPORT.mkdir(parents=True,exist_ok=True)
 with (REPORT/'matched_comparison.csv').open('w',newline='') as f: wri=csv.DictWriter(f,fieldnames=sorted(rows[0])); wri.writeheader(); wri.writerows(rows)
 with (REPORT/'full_prior_conditional.csv').open('w',newline='') as f: wri=csv.DictWriter(f,fieldnames=sorted(fs_o[0])); wri.writeheader(); wri.writerows(fs_o+fs_a)
 cost=[['item','count','scope'],['new_rl_runs',1,'B2 only'],['new_transitions',1935,'B2 actual Tcap-first'],['complete_ppo_updates',1,'B2'],['fragment_updates',1,'terminal Tcap fragment'],['full_new_training',0,'Full preserved'],['new_eval_episodes',38,'20 B2 dev10 + 18 Full prior switch'],['vlm_calls',0,'all'],['test_episodes',0,'all'],['extra_seed_runs',0,'all'],['shadow_forward','not_run','optional; action flip/TV NA']]
 with (REPORT/'cost_ledger.csv').open('w',newline='') as f:
  for row in cost: csv.writer(f).writerow(row)
 (REPORT/'Results_R3_Recovery.md').write_text(f'''# CP-DISR v1.3 R3-Recovery: matched N=2048 and Full prior switch\n\n## Scope and identity\n\nThis recovery ran only as `xushijie2@gpu03` with `/home/xushijie2/envs/lerobotpi0-xfs/bin/python` in the isolated recovery worktree. It did not resume or retrain Full, and it did not touch B0/R2.\n\n## Full durable boundary\n\nThe preserved Full checkpoint `n_002048.pt` was verified against SHA-256 `4b5f2a873fed2052db30ade97c4bc08e06f298fec8674db3d02a7f7f3309021c`; `update_complete_2.pt` was verified as `f9ff429ffd3db955b38d2b9e47a5b83800238609957a1f496953e721465cd4be`. The authoritative Full boundary is N=2048, T=9771.400000000713, two complete updates.\n\n## Matched B2 recovery\n\nB2 was initialized from fresh model/Adam/RNG/environment state with empty effective prior and strict DP/uP/Delta zero. Real Tcap-first stopping occurred at N=1935 and T=9319.000000000771, so N=2048 and a second complete update were not reached. There was one complete 1024-transition update and one terminal 911-transition fragment; no extension was attempted. N=0 and the actual final-N dev10 evaluations are persisted. The first-update self-check passed (1024 transitions, four epoch log rows, finite metrics, parameter L2 change 3.462288303750047, generation sidecars present).\n\n## Full prior switch\n\nThe same Full N=2048 checkpoint was evaluated with an empty prior for the frozen `S_dev=[D0_dev_00]` case and the four frozen S_train cases under both `Full@Original` and `Full@Absent`. Full@Original dev10 was reused from the original persisted evaluation; it was not rerun. Full@Absent covered all 10 dev10 cases (10/10 success; mean start discounted return 0.6350014580965666). The frozen nonempty-prior stratum remains D0_dev_00. S_train success was 3/4 under both conditions; DP/Delta opportunity and nonzero witnesses were zero in these four cases. Optional same-state shadow forward was not run, therefore action-flip denominator and TV are explicitly NA. Full@Absent is an inference-time switch, not B2 training.\n\n## Stall reconciliation\n\nThe old Full tail is classified `PPO_INTERNAL_STALL` with high confidence because the frozen training log contains the PPO update line at N=3072 immediately before the no-transition window. N=3072 is not treated as a completed update; the durable endpoint remains N=2048. No long reproduction or Full resume was performed.\n\n## Claims and limits\n\nThis is a matched-boundary recovery record, not an E8 completion. No test/VLM/extra seed/T_C/A_CAT/A_Q/A_B activity occurred.\n''',encoding='utf-8')
 (REPORT/'claim_evidence_table.md').write_text('''# Claim/evidence table\n\n| Claim | Evidence | Interpretation |\n|---|---|---|\n| Full durable boundary | `runs/v13_r3_recovery/full_checkpoint_verification.json` | N=2048, T=9771.400000000713, 2 complete updates; hashes verified |\n| Full stall phase | `stall_phase_reconciliation.md`, `stall_timeline.json`, `last_log_records.json` | PPO internal stall at attempted N=3072; not a completed update |\n| B2 actual endpoint | `runs/v13_r3_recovery/D0/B2/.../job_summary.json` | Tcap-first N=1935, 1 complete + 1 fragment; no N=2048 claim |\n| B2 first update | `b2_first_update_selfcheck.json`, `train_metrics.csv` | 1024 transitions, four epoch rows, finite losses, parameter change |\n| Full prior switch | `full_absent_dev10.json`, `full_s_train_original.csv`, `full_s_train_absent.csv` | Same Full checkpoint, prior-only intervention; Full@Absent is not B2 |\n''',encoding='utf-8')
 (REPORT/'unresolved_items.md').write_text('''# Unresolved items\n\n- B2 did not reach N=2048 or two complete updates because the fixed R3 Tcap was reached first; no automatic extension or resume was authorized.\n- Full same-state shadow forward was optional and not run; action-flip denominators and TV are NA.\n- The prior Full run remains a historical artifact under the original R3 worktree; this recovery does not rewrite its provenance.\n''',encoding='utf-8')
 w(STATUS,{'status':'COMPLETE_TCAP_FIRST','phase':'R3_RECOVERY_MATCHED_N2048','completed_at':datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),'account':'xushijie2','host':'gpu03','worktree':str(ROOT),'source_commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),'full_boundary':{'N':2048,'T':9771.400000000713,'complete_updates':2,'checkpoint_sha256':'4b5f2a873fed2052db30ade97c4bc08e06f298fec8674db3d02a7f7f3309021c'},'b2':{'N':1935,'T':9319.000000000771,'complete_updates':1,'fragment_updates':1,'eval_points':[0,1935]},'new_rl_runs':1,'new_transitions':1935,'new_complete_updates':1,'new_fragment_updates':1,'new_eval_episodes':38,'full_new_training':0,'vlm_calls':0,'test_episodes':0,'extra_seed_runs':0,'shadow_forward':'NOT_RUN'})
if __name__=='__main__': main()
