#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
import pandas as pd
def main():
 p=argparse.ArgumentParser();p.add_argument('--claim-scope',type=Path,required=True);p.add_argument('--final-results',type=Path,required=True);p.add_argument('--claim-map',type=Path,required=True);p.add_argument('--g4-r1',type=Path,required=True);p.add_argument('--policy-secondary',type=Path,required=True);p.add_argument('--artifact-index',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();scope=json.loads(a.claim_scope.read_text());d=pd.read_csv(a.final_results);supported=d[d.category=='supported_primary_result'].result_id.tolist();qualified=d[d.category=='qualified_or_inconclusive_primary_result'].result_id.tolist();negative=d[d.category=='unsupported_or_negative_result'].result_id.tolist()
 text=f'''# Final Research Report\n\n## 1. Research boundary\n\nThis M6 freeze is limited to the manual core reward representation. New training, data, main reward retuning, and test-driven revisions are forbidden by the final lock.\n\n## 2. Core evidence\n\nIndependent checkpoint inference, raw-prediction reward recomputation, and content-group statistics support: {', '.join(supported)}.\n\n## 3. Qualified evidence\n\n{', '.join(qualified) if qualified else 'None beyond explicit controlled-support qualifiers.'}\n\n## 4. Negative and excluded results\n\n{', '.join(negative)}. Coverage and unseen-order extension claims remain removed; policy is secondary/mixed; automatic graph discovery is not the main method.\n\n## 5. Reproducibility\n\nThe compact M6 index records all packaged evidence. The lightweight release provides checksum validation and external manifests for checkpoints, data, raw predictions, and distributions.\n\n## 6. Recommended paper positioning\n\nPosition PathGraph-SARM as a bounded, manually specified graph-structured reward representation with explicit recovery semantics, not as a general policy-improvement, scaling, or automatic-graph result.\n''';a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(text,encoding='utf-8')
if __name__=='__main__':main()
