python -m upgrade_v2.u3.cli provider-smoke --provider qwen ...
python -m upgrade_v2.u3.cli provider-smoke --provider deepseek ...
python -m upgrade_v2.u3.cli secret-scan ...
python -m upgrade_v2.u3.cli provider-smoke --provider qwen ...  # retry after user key update
python -m upgrade_v2.u3.cli provider-smoke --provider deepseek ...  # retry after user key update
